#:import test test
#:import Factory kivy.factory.Factory

<TestingButton>:
    test: "Testing Button"


<TestHeading>:
    size_hint_max_y: 36


<TestingMenu>:
    orientation: 'vertical'

    TestHeading:
        text: "SETUP TESTS"
    BoxLayout:
        orientation: 'horizontal'
        TestingButton:
            text: "Populate Database"
            on_release: Factory.DbPopulatePopup().open()
        TestingButton:
            text: "Initialize Inventory"
            on_release: Factory.InventoryInitPopup().open()

    TestHeading:
        text: "SEARCH AND VIEW TESTS"
    BoxLayout:
        orientation: 'horizontal'
        TestingButton:
            text: "Show Product"
            on_release: test.gui.test_product_view('Volt Prime', app.root)
        TestingButton:
            text: "Show Component"
            on_release: test.gui.test_component_view('Volt Prime Chassis Blueprint', app.root)
        TestingButton:
            text: "Show Relic"
            on_release: test.gui.test_relic_view(app.root)

    TestHeading:
        text: "SCREEN MANAGER TESTS"
    BoxLayout:
        orientation: 'horizontal'
        TestingButton:
            text: "Test AutoScreenManager"
            on_release: test.gui.test_AutoScreenManager(app.root)

    TestHeading:
        text: "UNIT TESTS"
    BoxLayout:
        orientation: 'horizontal'
        TestingButton:
            text: "DbEntryListing"
            on_release: test.gui.test_DbEntryListing_subclasses()

    Button:
        text: "Close App"
        on_release: app.stop()


<AutoScreenManagerTestingMenu>:
    orientation: 'vertical'

    TestHeading:
        text: "SLIDE TRANSITIONS"
    BoxLayout:
        orientation: 'horizontal'
        TestingButton:
            text: "Left"
            on_release:
        TestingButton:
            text: "Right"
            on_release:
        TestingButton:
            text: "Up"
            on_release:
        TestingButton:
            text: "Down"
            on_release:

    TestHeading:
        text: "REVERSE TRANSITION"
    TestingButton:
        text: "Reverse"
        on_release: test.gui.test_AutoScreenManager_reverse(root.parent.parent)